apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: gke-acm-bootstrap
spec:
  location: global
  endpoint:
    gkeCluster:
      resourceRef:
        external: //container.googleapis.com/projects/jetstack-paul/locations/europe-west2/clusters/gke-acm-bootstrap
