apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: gkehubfeaturemembership-sample
spec:
  projectRef:
    name: gkehubfeaturemembership-dep
  location: global
  membershipRef:
    name: gkehubfeaturemembership-dep
  featureRef:
    name: gkehubfeaturemembership-dep
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        syncRepo: "https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit"
        syncBranch: "master"
        policyDir: "config-connector"
        syncWaitSecs: "20"
        syncRev: "HEAD"
    policyController:
      enabled: true
      exemptableNamespaces:
        - "test-namespace"
      referentialRulesEnabled: true
      logDeniesEnabled: true
      templateLibraryInstalled: true
      auditIntervalSeconds: "20"
    binauthz:
      enabled: true
    hierarchyController:
      enabled: true
      enablePodTreeLabels: true
      enableHierarchicalResourceQuota: true
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: gkehubfeaturemembership-dep
  name: gkehubfeaturemembership-dep
spec:
  location: us-central1-a
  initialNodeCount: 1
  workloadIdentityConfig:
    # Workload Identity supports only a single namespace based on your project name.
    workloadPool: gkehubfeaturemembership-dep.svc.id.goog
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: gkehubfeaturemembership-dep
spec:
  projectRef:
    name: gkehubfeaturemembership-dep
  location: global
  # The resourceID must be "configmanagement" if you want to use Anthos config
  # management feature.
  resourceID: configmanagement
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: gkehubfeaturemembership-dep
  name: gkehubfeaturemembership-dep
spec:
  location: global
  authority:
    # Issuer must contain a link to a valid JWT issuer. Your ContainerCluster is one.
    issuer: https://container.googleapis.com/v1/projects/gkehubfeaturemembership-dep/locations/us-central1-a/clusters/gkehubfeaturemembership-dep
  description: A sample GKE Hub membership
  endpoint:
    gkeCluster:
      resourceRef:
        name: gkehubfeaturemembership-dep
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  name: gkehubfeaturemembership-dep
spec:
  name: Config Connector Sample
  organizationRef:
    # Replace "${ORG_ID?}" with the numeric ID for your organization
    external: "${ORG_ID?}"
  billingAccountRef:
    # Replace "${BILLING_ACCOUNT_ID?}" with the numeric ID for your billing account
    external: "${BILLING_ACCOUNT_ID?}"
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: gkehubfeaturemembership-dep
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: gkehubfeaturemembership-dep-1
spec:
  resourceID: container.googleapis.com
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: gkehubfeaturemembership-dep
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: gkehubfeaturemembership-dep-2
spec:
  resourceID: gkehub.googleapis.com
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: gkehubfeaturemembership-dep
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: gkehubfeaturemembership-dep-3
spec:
  resourceID: anthosconfigmanagement.googleapis.com
