apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: gke-acm-bootstrap
spec:
  projectRef:
    external: jetstack-paul
  location: global
  membershipRef:
    name: gke-acm-bootstrap
  featureRef:
    name: gke-acm-bootstrap
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        syncRepo: "https://github.com/paulwilljones/gke-acm-bootstrap"
        syncBranch: "develop"
        policyDir: "config-root"
        secretType: "none"
        syncWaitSecs: "5"
