# resources:
# - namespaces.yaml

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  releaseName: cert-manager
  namespace: cert-manager
  version: 1.8.0
#   includeCRDs: true
  valuesInline:
    installCRDs: true
    #deploymentAnnotations\.config\.kubernetes\.io/depends-on: apps/namespaces/external-secrets/Deployment/external-secrets
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: 15.9.0
  releaseName: prometheus
  namespace: prometheus
- name: grafana
  repo: https://grafana.github.io/helm-charts
  version: 6.29.4
  releaseName: grafana
  namespace: grafana
# - name: external-secrets
#   repo: https://charts.external-secrets.io
#   version: 0.5.3
#   releaseName: external-secrets
#   namespace: external-secrets
#   includeCRDs: false
#   valuesInline:
#     installCRDs: false # CRDs have status in the definition which fails reconciler https://g.co/cloud/acm-errors#knv1045
#     certController:
#       create: false
#     webhook:
#       create: false
# - name: external-dns
#   repo: https://charts.bitnami.com/bitnami
#   releaseName: external-dns
#   namespace: external-dns
  # valuesInline:
  #   rbac:
  #     clusterRole: false
#  version: 6.3.0
# - name: external-dns
#   repo: https://kubernetes-sigs.github.io/external-dns/
#   releaseName: external-dns
#   namespace: external-dns
#   version: 1.9.0
